- hosts: pltest
  become: yes
  remote_user: ec2-user
  tasks:
   - name: Remove root login
     replace: path=/etc/ssh/sshd_config regexp='^PermitRootLogin yes' replace='#PermitRootLogin no' backup=yes
   - name: start SSHD service
     service: name=sshd state=reloaded enabled=yes
  #Change permitRoot login in sshd conf    
