---
- hosts: localhost
  connection: local
  remote_user: root
  gather_facts: true
  tasks:
   - name: Create SACM user
     user: name=sacmlinux shell=/bin/bash createhome=yes groups=ssh 
     tags: user
   - name: Set ! in shadow
     shell: usermod -p! sacmlinux
     tags: pass
   - name: make .ssh dir
     file: path=/home/sacmlinux/.ssh state=directory owner=sacmlinux group=sacmlinux
     tags: .ssh
   - name: Copy Files
     copy: src=/root/playbook/authorized_keys dest=/home/sacmlinux/.ssh/ owner=sacmlinux group=sacmlinux
     tags: authkey
   - name: Install dmidecode
     yum: name=dmidecode state=latest
     tags: dmide
   - name: Add SUDO info
     lineinfile: path=/etc/sudoers line="{{item.line}}" state=present backup=yes validate='/usr/sbin/visudo -cf %s'
     when: (ansible_distribution == "Amazon") or (ansible_distribution == "SLES") or
           (ansible_distribution == "Redhat") and (ansible_distribution_major_version == "6")
     with_items:
      - { line: 'sacmlinux ALL=(root) NOPASSWD: /usr/sbin/dmidecode, /sbin/lsof, /sbin/fdisk -l, /sbin/dmsetup table, /sbin/multipath -ll' }
     tags: red6
   - name: SUDO to RHEL 7
     lineinfile: path=/etc/sudoers line="{{item.line}}" state=present backup=yes validate='/usr/sbin/visudo -cf %s'
     when: (ansible_distribution == "RedHat") and (ansible_distribution_major_version == "7")
     with_items:
      - { line: 'sacmlinux ALL=(root) NOPASSWD: /sbin/dmidecode, /sbin/lsof, /sbin/fdisk -l, /sbin/dmsetup table, /sbin/multipath -ll' }
     tags: red7
Based on OS Adding users
