---
#- import_playbook: user.yml
- hosts: localhost
  connection: loca
#  become: yes
#  become_method: sudo
  remote_user: root
  gather_facts: false
  vars:
   input: "{{ }}"
  tasks:
   - name: Add user to sudo group
     lineinfile: path=/etc/sudoers regexp=EOF line="{{item.line}}" state=present backup=yes validate='/usr/sbin/visudo -cf %s'
     with_items:
       - { line: '{{input}} ALL=(ALL) PASSWD:ALL  '}

