---
- hosts: pingfednew
  become: yes
  remote_user: ec2-user
  gather_facts: false
  vars:
   input: "{{ }}"
  tasks:
   - name: Add user to sudo group
     lineinfile: path=/etc/sudoers regexp=EOF line="{{item.line}}" state=present backup=yes validate='/usr/sbin/visudo -cf %s'
     with_items:
       - { line: '{{input}} ALL=(ALL) PASSWD: ALL '}

# Exec as ansible-playbook sudo.yml -e input=ku290295
#It will give root access to user ku290295.
