---
- hosts: infranp
  become: yes
  remote_user: ec2-user
  tasks:
   - name: Copy dir
     copy: src="../CarbonBlackLinux" dest=/home/ec2-user owner=root group=root 
     tags: one
   - name: change permission
     shell: chmod u+x /home/ec2-user/CarbonBlackLinux/CarbonBlackClientSetup-linux-v6.1.3.71227.sh
     tags: second
   - name: Install script 
     shell: /home/ec2-user/CarbonBlackLinux/CarbonBlackClientSetup-linux-v6.1.3.71227.sh
     tags: three
   - name: Check  CB status process
     shell: ps -A |grep cbdaemon
     register: hai
   - debug: var=hai
