---
- hosts: ttt
  become: yes
  remote_user: ec2-user
  gather_facts: false
  tasks:
   - name: Download files
     yum: name={{item}} state=latest
     tags: three
     loop:
      - autoconf
      - expat-devel 
      - libtool 
      - libnghttp2-devel 
      - pcre-devel
      - perl-core 
      - zlib-devel
