---
- hosts: localhost
  connection: local
  remote_user: root
  tasks:
   - name: User create
     user: name=jan210 createhome=yes shell=/bin/bash 
     when: (ansible_distribution == "RedHat")
     tags: whenred
   - name: Add SUDO info
     lineinfile: path=/etc/sudoers line="{{item.line}}" state=present backup=yes validate='/usr/sbin/visudo -cf %s'
     when: (ansible_distribution == "Amazon")
     with_items:
      - { line: 'sacmlinux ALL=(root) NOPASSWD: /sbin/dmidecode, /sbin/lsof, /sbin/fdisk -l, /sbin/dmsetup table, /sbin/multipath -ll' }
#     when: (ansible_distribution == "RedHat")
     tags: whenred1

